/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aryan
 */
public class EditEmployee_jFrame extends javax.swing.JFrame {
    private MyHashTable HT; // creates attribute HT of type MyHashTable
    /**
     * Creates new form EditJFrame
     */
    public EditEmployee_jFrame() {
        initComponents();
        
        invalidInput.setVisible(false);
        FTEInternalFrame.setVisible(false);
        PTEInternalFrame.setVisible(false);
    }    
    
    public void setMainHT(MyHashTable theRefVal) {
        HT = theRefVal; // initializes the variable
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PTERadioBtn = new javax.swing.JRadioButton();
        FTERadioBtn = new javax.swing.JRadioButton();
        empNumField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        deductRateField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        FTEInternalFrame = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        saveChangesBtn = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        PTEInternalFrame = new javax.swing.JInternalFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hourlyWageField = new javax.swing.JTextField();
        hoursPerWeekField = new javax.swing.JTextField();
        weeksPerYearField = new javax.swing.JTextField();
        invalidInput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Please enter the employee number of the employee that you want to edit:");

        jLabel2.setText("Employee Number");

        jLabel3.setText("First Name");

        lastNameLabel.setText("Last Name");

        jLabel5.setText("Deduct Rate");

        PTERadioBtn.setText("Part time");
        PTERadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTERadioBtnActionPerformed(evt);
            }
        });

        FTERadioBtn.setText("Full Time");
        FTERadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTERadioBtnActionPerformed(evt);
            }
        });

        empNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumFieldActionPerformed(evt);
            }
        });

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        deductRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductRateFieldActionPerformed(evt);
            }
        });

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        FTEInternalFrame.setVisible(true);

        jLabel6.setText("Salary");

        salaryField.setToolTipText("Gross Annual Salary");

        javax.swing.GroupLayout FTEInternalFrameLayout = new javax.swing.GroupLayout(FTEInternalFrame.getContentPane());
        FTEInternalFrame.getContentPane().setLayout(FTEInternalFrameLayout);
        FTEInternalFrameLayout.setHorizontalGroup(
            FTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTEInternalFrameLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        FTEInternalFrameLayout.setVerticalGroup(
            FTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTEInternalFrameLayout.createSequentialGroup()
                .addGroup(FTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveChangesBtn.setText("Apply Changes");
        saveChangesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesBtnActionPerformed(evt);
            }
        });

        resultLabel.setText("Employee Information: ");

        PTEInternalFrame.setVisible(true);

        jLabel9.setText("Hourly wage");

        jLabel10.setText("Hours per week");

        jLabel11.setText("Weeks per year");

        hourlyWageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyWageFieldActionPerformed(evt);
            }
        });

        hoursPerWeekField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursPerWeekFieldActionPerformed(evt);
            }
        });

        weeksPerYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeksPerYearFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PTEInternalFrameLayout = new javax.swing.GroupLayout(PTEInternalFrame.getContentPane());
        PTEInternalFrame.getContentPane().setLayout(PTEInternalFrameLayout);
        PTEInternalFrameLayout.setHorizontalGroup(
            PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTEInternalFrameLayout.createSequentialGroup()
                .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTEInternalFrameLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31)
                        .addComponent(hourlyWageField))
                    .addGroup(PTEInternalFrameLayout.createSequentialGroup()
                        .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hoursPerWeekField, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(weeksPerYearField))))
                .addContainerGap())
        );
        PTEInternalFrameLayout.setVerticalGroup(
            PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTEInternalFrameLayout.createSequentialGroup()
                .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(hourlyWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(hoursPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(weeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        invalidInput.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(resultLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                            .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(empNumField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deductRateField)))
                                    .addComponent(lastNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(FTEInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(PTERadioBtn)
                                .addGap(18, 18, 18)
                                .addComponent(FTERadioBtn)
                                .addGap(94, 94, 94)
                                .addComponent(saveChangesBtn)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(invalidInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(PTEInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(empNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(deductRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(FTEInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(PTERadioBtn)
                                            .addComponent(FTERadioBtn))
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveChangesBtn)
                                        .addGap(60, 60, 60)))
                                .addComponent(resultLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(invalidInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PTEInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void exitAddNewEmployee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAddNewEmployee
        // TODO add your handling code here:     
        this.dispose(); // Make this window disappear
    }//GEN-LAST:event_exitAddNewEmployee

    private void clickedFTERadioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedFTERadioButton
        // TODO add your handling code here:
    }//GEN-LAST:event_clickedFTERadioButton

    private void clickedPTERadioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedPTERadioButton

    }//GEN-LAST:event_clickedPTERadioButton

    private void InpWeeksPerYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InpWeeksPerYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InpWeeksPerYearActionPerformed

    private void InpLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InpLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InpLastNameActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FTERadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTERadioBtnActionPerformed
        // TODO add your handling code here:
        PTEInternalFrame.setVisible(false);  // PTE stuff
        FTEInternalFrame.setVisible(true);   // FTE stuff
    }//GEN-LAST:event_FTERadioBtnActionPerformed

    private void empNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumFieldActionPerformed
        // TODO add your handling code here:
        resultLabel.setText(" ");
        // Autofills previous info in fields to be edited
        int empNum;
        try{
            empNum = Integer.parseInt(empNumField.getText());
        }
        catch(java.lang.NumberFormatException e){
            resultLabel.setText("Employee number invalid!");
            resultLabel.setVisible(true);
            return;
        }
        // Displays emp info on GUI
        EmployeeInfo theEmp = HT.getEmployee(empNum);
        if(theEmp == null){
            resultLabel.setText("Employee #" + empNum + " not found!");
            resultLabel.setVisible(true);
            return;
        }
        firstNameField.setText(theEmp.firstName);
        lastNameField.setText(theEmp.lastName);
        deductRateField.setText(String.valueOf(theEmp.deductRate));
        
        if(theEmp instanceof FTE){
            FTE theFTE = (FTE)theEmp;   // Casts object of super class in subclass FTE
            salaryField.setText(String.valueOf(theFTE.yearlySalary));
        }
        else{
            PTE thePTE = (PTE)theEmp;   // Casts object of super class in subclass FTE
            hourlyWageField.setText(String.valueOf(thePTE.hourlyWage));
            hoursPerWeekField.setText(String.valueOf(thePTE.hoursPerWeek));
            weeksPerYearField.setText(String.valueOf(thePTE.weeksPerYear));
        }
        
    }//GEN-LAST:event_empNumFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void deductRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deductRateFieldActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void hourlyWageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyWageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyWageFieldActionPerformed

    private void hoursPerWeekFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursPerWeekFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursPerWeekFieldActionPerformed

    private void weeksPerYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeksPerYearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weeksPerYearFieldActionPerformed

    private void PTERadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTERadioBtnActionPerformed
        // TODO add your handling code here:
        FTEInternalFrame.setVisible(false);  // FTE stuff
        PTEInternalFrame.setVisible(true);   // PTE stuff
    }//GEN-LAST:event_PTERadioBtnActionPerformed

    private void saveChangesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesBtnActionPerformed
        // TODO add your handling code here:
        int theEmpNum;
        try{
            theEmpNum = Integer.parseInt(empNumField.getText());
        }
        catch(java.lang.NumberFormatException e){
            resultLabel.setText("Employee number invalid!");
            return;
        }
        // Displays emp info on GUI
        EmployeeInfo theEmp = HT.getEmployee(theEmpNum);
        if(theEmp == null){
            resultLabel.setText("Employee #" + theEmpNum + " not found!");
            return;
        }
        
        // Data validation for deductRate
        double theDeductRate;
        try{
            theDeductRate = Double.parseDouble(deductRateField.getText());
            if(theDeductRate < 0 || theDeductRate > 1)  throw new java.lang.NumberFormatException();
        }
        catch(java.lang.NumberFormatException e){
            resultLabel.setText("Deduct rate invalid!");
            return;
        }
        
        String theFirstName = firstNameField.getText();
        String theLastName = lastNameField.getText();
        
        // copied from addnewemp
        // FULL TIME EMPLOYEE
        if (FTERadioBtn.isSelected()) {          
            String strSalary = salaryField.getText();
            double Salary;
            try{
                Salary = Double.parseDouble(strSalary);
            }
            catch(java.lang.NumberFormatException e){
                lastNameLabel.setText("Employee salary invalid!");
                return;
            }
            FTE theFTE = new FTE(theEmpNum, theFirstName, theLastName,
                        0, theDeductRate, Salary);
            System.out.println("Salary of the FTE is " + Salary);
            HT.removeEmployee(theEmpNum);
            HT.addEmployee(theFTE);
        }
        
        // PART TIME EMPLOYEE
        else if (PTERadioBtn.isSelected()) {
            // Get the hourly wage, hours per week, weeks per year
            // Instantiate an PTE with the info for that employee
            // Add that employee to the hash table
            double hourlyWage;
            int hoursPerWeek, weeksPerYear;
            
            try{
                hourlyWage = Double.parseDouble(hourlyWageField.getText());
                hoursPerWeek = Integer.parseInt(hoursPerWeekField.getText());
                weeksPerYear = Integer.parseInt(weeksPerYearField.getText());
            }
            catch(java.lang.NumberFormatException e){
                invalidInput.setVisible(true);
                invalidInput.setText("Employee wage info invalid!");
                return;
            }
            HT.removeEmployee(theEmpNum);
            HT.addEmployee(new PTE(theEmpNum, theFirstName, theLastName,
                        0, theDeductRate, hourlyWage, hoursPerWeek, weeksPerYear));
        }
        // If neither FTE nor PTE was selected notify user to click select one
        else{
            invalidInput.setVisible(true);
            invalidInput.setText(    "MUST SELECT EITHER FTE or PTE!");
            return;
        }
        resultLabel.setText("Edited new employee:  " + empNumField.getText() + " "
                        + theFirstName + " " + theLastName);       // cld change back to invalidInput
        resultLabel.setVisible(true);
        empNumField.setText("");
        firstNameField.setText("");
        lastNameField.setText("");
        deductRateField.setText("");
    }//GEN-LAST:event_saveChangesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee_jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame FTEInternalFrame;
    private javax.swing.JRadioButton FTERadioBtn;
    private javax.swing.JInternalFrame PTEInternalFrame;
    private javax.swing.JRadioButton PTERadioBtn;
    private javax.swing.JTextField deductRateField;
    private javax.swing.JTextField empNumField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField hourlyWageField;
    private javax.swing.JTextField hoursPerWeekField;
    private javax.swing.JLabel invalidInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField salaryField;
    private javax.swing.JButton saveChangesBtn;
    private javax.swing.JTextField weeksPerYearField;
    // End of variables declaration//GEN-END:variables

}